---
- name: Install Zabbix Server on Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Download Zabbix repository
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu24.04_all.deb
        dest: /tmp/zabbix-release_latest_7.2+ubuntu24.04_all.deb

    - name: Install Zabbix repository package
      ansible.builtin.apt:
        deb: /tmp/zabbix-release_latest_7.2+ubuntu24.04_all.deb

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Zabbix server, frontend, and agent
      ansible.builtin.apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present
        update_cache: yes

    - name: Clean up downloaded repository package
      ansible.builtin.file:
        path: /tmp/zabbix-release_latest+ubuntu24.04_all.deb
        state: absent
        
    - name: Configure DBPassword in zabbix_server.conf
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: 'DBPassword=password'
        state: present

  handlers:
    - name: Restart Zabbix server, agent, and Apache
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2
