---
- name: Install and Configure Zabbix Server
  hosts: all
  become: true
  tasks:

    - name: Download Zabbix repository package
      get_url:
        url: https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu24.04_all.deb
        dest: /tmp/zabbix-release_latest_7.2+ubuntu24.04_all.deb

    - name: Install Zabbix repository package
      apt:
        deb: /tmp/zabbix-release_latest_7.2+ubuntu24.04_all.deb

    - name: Update apt repositories
      apt:
        update_cache: yes

    - name: Install Zabbix server, frontend, agent
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    - name: Create Zabbix database and user
      mysql_db:
        name: zabbix
        state: present
        encoding: utf8mb4
        collation: utf8mb4_bin
      become_user: root

    - name: Create Zabbix user with privileges
      mysql_user:
        name: zabbix
        password: password
        priv: "zabbix.*:ALL"
        state: present
      become_user: root

    - name: Set global log_bin_trust_function_creators
      mysql_variables:
        variable: log_bin_trust_function_creators
        value: 1
        state: present
      become_user: root

    - name: Import initial schema and data for Zabbix
      command: >
        zcat /usr/share/zabbix/sql-scripts/mysql/server.sql.gz | 
        mysql --default-character-set=utf8mb4 -uzabbix -ppassword Zabbix
      become_user: root

    - name: Disable log_bin_trust_function_creators after import
      mysql_variables:
        variable: log_bin_trust_function_creators
        value: 0
        state: present
      become_user: root

    - name: Configure DBPassword in zabbix_server.conf
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: 'DBPassword=password'
        state: present

    - name: Restart Zabbix server, agent, and Apache
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2
